source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'SDWebImage'
pod 'TTTAttributedLabel'
pod 'RegexKitLite'
pod 'hpple'
pod 'MBProgressHUD'
pod 'ODRefreshControl'
pod 'TPKeyboardAvoiding'
pod 'JDStatusBarNotification'
pod 'BlocksKit'
pod 'ReactiveCocoa'