source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'TTTAttributedLabel', '1.10.1'
pod 'RegexKitLite', '4.0'
pod 'hpple', '0.2.0'
pod 'MBProgressHUD', '0.9'
pod 'TPKeyboardAvoiding', '1.2.4'
pod 'JDStatusBarNotification', '1.4.9'
pod 'BlocksKit', '2.2.5'
pod 'ReactiveCocoa', '2.3.1'
pod 'MMMarkdown', '0.3'
pod 'Masonry', '0.5.3'
pod 'NYXImagesKit', '2.3'
pod 'UIImage+BlurredFrame', '0.0.4'
pod 'POP+MCAnimate', '2.0.1'
